apiVersion: v1
kind: Service
metadata:
  name: wibit-service
spec:
  selector:
    app: wibit-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wibit-app
spec:
  selector:
    matchLabels:
      app: wibit-app
  replicas: 1
  template:
    metadata:
      labels:
        app: wibit-app
    spec:
      securityContext:
        runAsGroup: 5000
        runAsUser: 5000
      containers:
        - name: wibit-app
          image: docker.io/andrzejstarzyk/suu_project_app
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
          ports:
            - containerPort: 5000
